name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.9.3' # The Go version to download (if necessary) and use.
    - run: make install-deps && make dist image 
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jecklgamis/go-api-server-template:$(date +%s)
